name: R Quick Test

on:
  workflow_dispatch:   # Actions 탭에서 수동 실행 버튼 표시

jobs:
  run-r:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # 안전장치
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'   # 원하면 다른 버전으로 변경 가능

      - name: Run R script
        run: Rscript test.R

      - name: Upload result artifact
        uses: actions/upload-artifact@v4
        with:
          name: r-test-output
          path: result.txt
          if-no-files-found: error
